### ISSUE TITLE
Potential addition: describe how futures are different from lazy evaluation

### ISSUE THREAD

**Issue by alexpghayes** [HenrikBengtsson/article-bengtsson-future#9]
Many R materials describe R's lazy evaluation mechanisms, and these descriptions often look quite similar to the explanation you've given of futures. It may be useful to compare and contrast lazy evaluation and futures briefly in the article. I realized today I don't actually know myself if there are meaningful differences -- futures can run asynchronously, and there's environment stuff, but are there other important differences? Is "futures as asynchronous lazy evaluation" a good mental model? I'm especially curious about the case where you create 3 futures but only have 2 workers, so that you block on the 3rd future. The same code without futures wouldn't block and would just wait until the 3rd value was explicitly requested, no? Anyway, thanks for the article!

**Comment by HenrikBengtsson** [comment]
Hi Alex,

thank you for this feedback.  It's something I haven't considered adding.  I have to think about if this can be incorporated in the article in a natural way.  Until then, here are some quick follow-ups:

> ... futures can run asynchronously, and there's environment stuff, but are there other important differences?

Yes, there are important differences.  The most important difference is a future "freezes" the variables needed to resolve the future expression _in the moment the future is created_, which means all globals are "force" resolved.  (This happens regardless of whether parallel or sequential processing is taking place.) In contrast, R's lazy evaluation does not do this.  For example, if an object/argument is not used, then it not resolved in lazy evaluation.  Also, if the object changes between the call and the use, lazy evaluation will use a different value than what you'd get from when eager evaluation would be used.  Eager evaluation can be emulated using `force()`.

There is related concept of delayed assignments in base R, which creates a _promise_ (a key player in lazy evaluation).  Delayed assignments somewhat correspond to _lazy_ future assignments, e.g.

```r
library(future)
a <- Sys.time()
delayedAssign("b", Sys.time())
futureAssign("c", Sys.time())
Sys.sleep(10)
d <- Sys.time()
print(a)
[1] "2020-08-21 18:21:55 PDT"
print(b)
[1] "2020-08-21 18:22:05 PDT"
print(c)
[1] "2020-08-21 18:21:55 PDT"
print(d)
[1] "2020-08-21 18:22:05 PDT"
```

Note how the future assign resolved the "input" when the future was created whereas the delayed assignment only resolved it when needed.

I don't mention `futureAssign()` in the article because it belongs to rare use cases, and exists mostly as an explicit function call alternative to `b %<-% Sys.time()`.


> Is "futures as asynchronous lazy evaluation" a good mental model?

Based on the above, important difference, I would say no.


> I'm especially curious about the case where you create 3 futures but only have 2 workers, so that you block on the 3rd future.

I think you're thinking of:
```r
f1 <- future({ slow_fcn(xs[1]) })
f2 <- future({ slow_fcn(xs[2]) })
f3 <- future({ slow_fcn(xs[3]) })
```

Correct, with two workers, and if none of the first two do not complete before we try to create `f3`, then, yes, it blocks (as mentioned in the article).


> The same code without futures wouldn't block and would just wait until the 3rd value was explicitly requested, no?

I take it as you mean:

```r
v1 <- slow_fcn(xs[1])
v2 <- slow_fcn(xs[2])
v3 <- slow_fcn(xs[3])
```

If so, there is no lazy evaluation taking place here.  The first statement will block until `slow_fcn()` completes - only then will `v1` be assign the value, and R will continue to the second statement, and so on.


Hope this clarifies it a bit more.

**Comment by HenrikBengtsson** [comment]
I think I've found a natural place to touch on the difference between [lazy] future evaluation and R's lazy evaluation. I've added a footnote to "A lazy future defers[FOOTNOTE] the evaluation of its expression until we the evaluation of its expression until we use `resolved()` to query if it is resolved or until we use `value()` to collect its value." in Section 'Future work':

_FOOTNOTE: Although a lazy future defers the evaluation to a later time, contrary to R’s lazy evaluation and promises, a
future records all dependent variables (“globals”) when it is created, which means it will resolve to the same value
even if those globals change after the future was created and before it was resolved. This also means that lazy and
eager futures give the same value._

Thanks again for the comment/questions.
